######################################################################
# Automatically generated by qmake (3.0) Fri Sep 22 19:28:34 2017
######################################################################

TEMPLATE = app
TARGET = lexi
INCLUDEPATH += .
OBJECTS_DIR = obj
QT += widgets

# Input
SOURCES += main.cpp \
    abstract/abstractwidget.cpp

HEADERS += \
    abstract/abstractwidget.h

